pub(crate) mod catalog;
pub mod client;
pub(crate) mod context_ops;
pub mod embedding;
pub mod error;
pub(crate) mod evidence;
pub mod fs;
pub mod index;
pub mod ingest;
pub mod models;
pub mod pack;
pub mod parse;
pub mod qdrant;
pub(crate) mod quality;
pub(crate) mod queue_policy;
pub(crate) mod release_gate;
pub mod retrieval;
pub(crate) mod security_audit;
pub mod session;
pub mod state;
pub mod uri;

pub use client::AxiomMe;
pub use error::{AxiomError, Result};
pub use fs::LocalContextFs;
pub use models::*;
pub use qdrant::{QdrantConfig, QdrantMirror};
pub use session::Session;
pub use uri::{AxiomUri, Scope};
